apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-nginx
  name: php-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: php-nginx
    spec:
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: php-config-volume
        configMap:
          name: php-config
      containers:
      - name: nginx
        image: nginx:alpine
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 150m
            memory: 100Mi
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-vhosts.conf
        ports:
        - containerPort: 8080
      - name: php
        image: app-nginx:latest
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 150m
            memory: 100Mi
        volumeMounts:
        - name: php-config-volume
          mountPath: /usr/local/etc/php-fpm.conf
          subPath: php-fpm.conf
        - name: php-config-volume
          mountPath: /usr/local/etc/php-fpm.d/www.conf
          subPath: www.conf
        ports:
        - containerPort: 9000
          protocol: TCP
        imagePullPolicy: IfNotPresent
