apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-swoole
  name: php-swoole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-swoole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: php-swoole
    spec:
      containers:
      - name: php
        image: php-swoole:latest
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 150m
            memory: 100Mi
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
